application: dtmportfolio
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /(.+\.(html|css|gif|png|jpg|js))$
  static_files: \1
  upload: .+\.(html|css|gif|png|jpg|js)$
  application_readable: true

- url: /.*
  static_files: home.html
  upload: home.html
  application_readable: true